### ISSUE TITLE
Support for `data` attributes?

### ISSUE THREAD

**Issue by johanfforsberg** [paveldedik/ludic#47]
Hi, Ludic looks very neat!

I could not figure out how to add `data` attributes to an element, e.g. `data-stuff="123"`. Am I missing something, or is it not yet implemented?

**Comment by paveldedik** [comment]
Hi @johanfforsberg 

you are right, it is not supported right now. I was thinking about this already and what blocked me was thinking about how it should work so that type hinting works. Well, there is probably no way currently to have it supported with typing.

But that doesn't mean it shouldn't be possible. Currently it raises a `KeyError` when unknown attribute appears. I think I'll change that but I also want to add proper support for the data attribute.

So I think I'll implement it to make `data_stuff="123"` work as a key-word argument.

I'll do that ASAP, next week latest, it seems important.

Thank you for opening the issue!

**Comment by paveldedik** [comment]
I decide to implement it as it was a simple fix.

It will be released today and the way it'll work is using the `data_stuff="value"` attribute.

Is this ok for you?

I was also thinking about using `data={"stuff": "value", "foo": "bar"}` which would render `data-stuff` and `data-bar` but there are issues with this - like the `<object>` HTML element which uses the `data` attribute for something else.

**Comment by johanfforsberg** [comment]
Wow, that was fast! To me, `data_stuff` seems to be the most intuitive syntax as it's consistent with how other attributes map to HTML.

**Comment by paveldedik** [comment]
The fix is released btw.
